=== organicoil/ITROI/LB_1_2/DAN_1_2/src/main/java/ua/nure/publisher/entity/generated/magazines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:mag="http://ua.nure/magazines/"
            targetNamespace="http://ua.nure/magazines/"
            elementFormDefault="qualified">

    <xsd:simpleType name="id">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:totalDigits value="10"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="entity">
        <xsd:attribute name="id" type="mag:id" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="title">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="20"/>
            <xsd:pattern value="[\w\s]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="price">
        <xsd:restriction base="xsd:decimal">
            <xsd:fractionDigits value="3"/>
            <xsd:minExclusive value="0"/>
            <xsd:maxExclusive value="1000"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="perMonthPublishCount">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="31"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="publishType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="daily"/>
            <xsd:enumeration value="monthly"/>
            <xsd:enumeration value="twicePerMonth"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="publishing">
        <xsd:choice>
            <xsd:element name="perMonthPublishCount" type="mag:perMonthPublishCount"/>
            <xsd:element name="publishType"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="category">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="politics"/>
            <xsd:enumeration value="sport"/>
            <xsd:enumeration value="it"/>
            <xsd:enumeration value="none"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="magazine">
        <xsd:complexContent>
            <xsd:extension base="mag:entity">
                <xsd:all>
                    <xsd:element name="title" type="mag:title"/>
                    <xsd:element name="description" type="xsd:string"/>
                    <xsd:element name="price" type="mag:price"/>
                    <xsd:element name="publishing" type="mag:publishing"/>
                    <xsd:element name="category" type="mag:category" default="none"/>
                </xsd:all>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="magazines">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="magazine" type="mag:magazine" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== organicoil/ITROI/LB_1_2/DAN_1_2/src/test/resources/xml/magazines.xml
<?xml version="1.0" encoding="UTF-8"?>
<magazines xmlns="http://ua.nure/magazines/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ua.nure/magazines/ ../xsd/magazines.xsd">
  <magazine id="1">
    <title>Title1</title>
    <description>Desc1</description>
    <price>99.0</price>
    <publishing>
      <perMonthPublishCount>4</perMonthPublishCount>
    </publishing>
    <category>it</category>
  </magazine>
  <magazine id="2">
    <title>Title2</title>
    <description>Desc2</description>
    <price>999.0</price>
    <publishing>
      <perMonthPublishCount>3</perMonthPublishCount>
    </publishing>
    <category>sport</category>
  </magazine>
</magazines>

=== organicoil/ITROI/LB_1_2/src/main/resources/xml/magazines.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="magazines.xsl"?>
<mag:magazines xmlns:mag="http://ua.nure/magazines/"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ua.nure/magazines/ ../xsd/magazines.xsd">

    <mag:magazine id="1">
        <mag:title>Cool Mag 1</mag:title>
        <mag:description>-</mag:description>
        <mag:price>999</mag:price>
        <mag:publishing>
            <mag:perMonthPublishCount>2</mag:perMonthPublishCount>
        </mag:publishing>
        <mag:category>it</mag:category>
    </mag:magazine>

    <mag:magazine id="2">
        <mag:title>Cool Mag 2</mag:title>
        <mag:description>-</mag:description>
        <mag:price>123</mag:price>
        <mag:publishing>
            <mag:perMonthPublishCount>3</mag:perMonthPublishCount>
        </mag:publishing>
        <mag:category>politics</mag:category>
    </mag:magazine>

    <mag:magazine id="3">
        <mag:title>Cool Mag 3</mag:title>
        <mag:description>-</mag:description>
        <mag:price>321</mag:price>
        <mag:publishing>
            <mag:publishType>daily</mag:publishType>
        </mag:publishing>
        <mag:category>sport</mag:category>
    </mag:magazine>

</mag:magazines>
